LPS-158711_WIP
lfbesada/liferay-portal pull request #96
Opened 2022-07-28 11:30 UTC by BarbaraCabrera

2022-07-28 11:30 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-08-04 07:20 UTC, lfbesada requested changes

2022-08-04 07:20 UTC, lfbesada commented on modules/apps/asset/asset-categories-admin-web/src/main/java/com/liferay/asset/categories/admin/web/internal/display/context/AssetCategoriesDisplayContext.java
> +			return LocalizationUtil.updateLocalization(
He estado mirando como se hace en basic_info para Journal y cuando es null, lo que se pasa en el xml es una cadena en blanco, aquí deberíamos entonces hacer return StringPool.BLANK

2022-08-04 07:20 UTC, lfbesada commented on modules/apps/asset/asset-categories-admin-web/src/main/resources/META-INF/resources/category/details.jsp
> +					<liferay-ui:input-localized
Faltan unos cuantos atributos respecto a lo que te puse de ejemplo en el basic_info.jsp: availableLocales y selectedLanguageId, también está ignoreRequestValue pero creo que ese no aplica

2022-08-05 07:19 UTC, lfbesada commented
ci:test:sf

2022-08-05 07:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/3015/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/3015/jenkins-report.html">here</a>.</b></p>

2022-08-05 07:23 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c123a8a2c1fe12c495f67fc84c19285102cf206e">c123a8a2c1fe12c495f67fc84c19285102cf206e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/BarbaraCabrera/liferay-portal/tree/LPS-158711_WIP">LPS-158711_WIP</a><br/>Branch GIT ID: <a href="https://github.com/BarbaraCabrera/liferay-portal/commit/8bc31cc53a4628e65346d3086db7182a02b66ae2">8bc31cc53a4628e65346d3086db7182a02b66ae2</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/3015/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/3015/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: There should be an empty line before assigning value to variable 'localization', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/missing_empty_line_check.markdown: ./modules/apps/asset/asset-categories-service/src/main/java/com/liferay/asset/categories/internal/search/spi/model/index/contributor/AssetCategoryModelDocumentContributor.java 72 (Checkstyle:MissingEmptyLineCheck)
     [java] 2: ./modules/apps/asset/asset-categories-service/src/main/java/com/liferay/asset/categories/internal/search/spi/model/index/contributor/AssetCategoryModelDocumentContributor.java expected:&lt;...), StringPool.BLANK,[
     [java]           "description", assetCategory.getDefaultLanguageId()));
     [java] 
     [java]     for (String descriptionAvailableLanguageId :
     [java]         descriptionAvailableLanguageIds) \{
     [java] 
     [java]       String description = _html.stripHtml(
     [java]         assetCategory.getDescription(descriptionAvailableLanguageId));
     [java] 
     [java]       document.addText(
     [java]         localization.getLocalizedName(
     [java]           Field.DESCRIPTION, descriptionAvailableLanguageId),
     [java]         description);
     [java] 
     [java]       _searchLocalizationHelper.addLocalizedField(
     [java]         document, Field.DESCRIPTION, siteDefaultLocale,
     [java]         LocalizationUtil.getLocalizationMap(
     [java]           LocalizationUtil.updateLocalization(
     [java]             LocalizationUtil.getLocalizationMap(description),
     [java]             StringPool.BLANK, "description",
     [java]             assetCategory.getDefaultLanguageId())));
     [java]     \}
     [java] 
     [java]     document.addText(Field.NAME, assetCategory.getName());
     [java] 
     [java]     _searchLocalizationHelper.addLocalizedField(
     [java]       document, Field.TITLE, siteDefaultLocale,
     [java]       assetCategory.getTitleMap());
     [java] 
     [java]     document.addKeyword("treePath", assetCategory.getTreePath());
     [java]     document.addLocalizedKeyword(
     [java]       "localized_title",
     [java]       LocalizationUtil.populateLocalizationMap(
     [java]         assetCategory.getTitleMap(),
     [java]         assetCategory.getDefaultLanguageId(),
     [java]         assetCategory.getGroupId()),
     [java]       true, true);
     [java]   \}
     [java] 
     [java]   protected Locale getSiteDefaultLocale(AssetCategory assetCategory) \{</pre></details></html>

2022-08-05 07:25 UTC, lfbesada commented
![red_card](https://user-images.githubusercontent.com/84471361/183024836-ccea5a50-1625-4c2a-b54d-3713feef56c0.gif)

2022-08-05 07:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/3015/">test-portal-source-format#3015</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/3015/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lfbesada/liferay-portal/pull/96">lfbesada#96</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1937474657">[master] ci:test:sf - BarbaraCabrera &gt; lfbesada - PR#96 - 2022-08-05[00:20:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/11191/">publish-testray-report#11191</a><br/></div></div>

2022-08-05 07:53 UTC, lfbesada requested changes

2022-08-05 07:53 UTC, lfbesada commented on modules/apps/asset/asset-categories-admin-web/src/main/java/com/liferay/asset/categories/admin/web/internal/display/context/AssetCategoriesDisplayContext.java
> +		if (Validator.isNotNull(_defaultLanguageId)) {
La variable no debería llamarse defaultLanguageId porque es ambiguo con el _defaultLanguageId, podrías llamarla _languageId o _selectedLanguageId pero no default

2022-08-05 07:53 UTC, lfbesada commented on modules/apps/asset/asset-categories-admin-web/src/main/java/com/liferay/asset/categories/admin/web/internal/display/context/AssetCategoriesDisplayContext.java
> +		return _defaultLanguageId;
En estos casos, cuando usamos una variable para "cachear" el resultado de un método, tal y como haces aquí, el método siempre empieza con que si la variable no es null la retorno directamente. Por ello nunca asignamos la variable en el método más que una vez, dado que si hay concurrencia (dos llamadas al mismo tiempo al mismo método) puede pasar que el segundo acabe retornando un valor no deseado, porque coja la primera asignación de la variable que ha hecho el otro.
Para estos casos, usamos una variable intermedia que finalmente asignamos a la variable que toca, en este caso, sería algo así:

```
public String getSelectedLanguageId(AssetCategory assetCategory) {
		if (Validator.isNotNull(_selectedLanguageId)) {
			return _selectedLanguageId;
		}

		String selectedLanguageId = ParamUtil.getString(
			_httpServletRequest, "languageId");

		if (Validator.isNull(selectedLanguageId)) {
			selectedLanguageId = getDefaultLanguageId(assetCategory);
		}

		_selectedLanguageId = selectedLanguageId;

		return _selectedLanguageId;
	}
```

2022-08-05 07:53 UTC, lfbesada commented on modules/apps/asset/asset-categories-service/src/main/java/com/liferay/asset/categories/internal/search/spi/model/index/contributor/AssetCategoryModelDocumentContributor.java
> +		}
El modelo que hay que reproducir aquí es este: https://github.com/liferay/liferay-portal/blob/91a5e132c2a608b8906bd8c3983769a26d4c14cd/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/search/spi/model/index/contributor/JournalArticleModelDocumentContributor.java#L99-L113 échale un vistazo que aquí estas haciendo cosas que no tocan

2022-08-05 07:53 UTC, lfbesada commented on modules/apps/asset/asset-categories-service/src/main/java/com/liferay/asset/categories/internal/search/spi/model/index/contributor/AssetCategoryModelDocumentContributor.java
> +		}
Por otra parte creo que aquí:
`LocalizationUtil.updateLocalization(
					assetCategory.getDescriptionMap(), StringPool.BLANK,
					"description", assetCategory.getDefaultLanguageId())`
devolverá lo mismo que 
`assetCategory.getDescription()`
Porque ese proceso ya lo hemos hecho antes de persistir la categoría, y el segundo caso tiene mucho mejor rendimiento.
Porfa, debúgalo o pon trazas para comnprobar si son lo mismo y, si lo son, cambialo pot el getDescription() directamente

2022-08-05 07:53 UTC, lfbesada commented on modules/apps/asset/asset-categories-admin-web/src/main/resources/META-INF/resources/view_asset_categories.jsp
> +								value="<%= curCategory.getDescription(locale) %>"
Esto no es una solución, se romperá, no puedes poner HTML dentro de un atributo de un tag. Creo que aquí habría que cambiar el tag para usarlo <liferay-ui:search-container-column-text attributes ...> assetCategory.getDescription(languageId) </liferay-ui:search-container-column-text>

2022-08-07 21:38 UTC, BarbaraCabrera commented
ci:test:sf

2022-08-07 21:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/2454/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2454/jenkins-report.html">here</a>.</b></p>

2022-08-07 21:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/47286ee27281b2b50bbbb738ff9d3ea6d78ff368">47286ee27281b2b50bbbb738ff9d3ea6d78ff368</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/BarbaraCabrera/liferay-portal/tree/LPS-158711_WIP">LPS-158711_WIP</a><br/>Branch GIT ID: <a href="https://github.com/BarbaraCabrera/liferay-portal/commit/87d4123bd7f8826e9053d8efbd49253b19335855">87d4123bd7f8826e9053d8efbd49253b19335855</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/2454/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2454/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/commerce/commerce-product-content-web/src/main/java/com/liferay/commerce/product/content/web/internal/asset/display/page/portlet/AssetCategoryAssetDisplayPageFriendlyURLResolver.java expected:&lt;...iption(languageId)),[
     [java]       ]httpServletRequest);...&gt; but was:&lt;...iption(languageId)),[ ]httpServletRequest);...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:442)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:284)
[stopwatch] [run.batch.test.action: 58.314 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:450: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:593: Java returned: 1
      [get] Getting: http://test-1-37/job/test-portal-source-format/2454//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20220807144117553.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20220807144117553.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null634537229.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null2066877127
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 161ms
[junitreport] Deleting: /tmp/null2066877127
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 08-07-2022 14:41:19:679 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</pre></details></html>

2022-08-07 21:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/2454/">test-portal-source-format#2454</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2454/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lfbesada/liferay-portal/pull/96">lfbesada#96</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1939068863">[master] ci:test:sf - BarbaraCabrera &gt; lfbesada - PR#96 - 2022-08-07[14:38:51]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/9450/">publish-testray-report#9450</a><br/></div></div>

2022-08-07 21:52 UTC, BarbaraCabrera commented
ci:test:sf

2022-08-07 21:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/3043/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/3043/jenkins-report.html">here</a>.</b></p>

2022-08-07 21:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/47286ee27281b2b50bbbb738ff9d3ea6d78ff368">47286ee27281b2b50bbbb738ff9d3ea6d78ff368</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/BarbaraCabrera/liferay-portal/tree/LPS-158711_WIP">LPS-158711_WIP</a><br/>Branch GIT ID: <a href="https://github.com/BarbaraCabrera/liferay-portal/commit/39ac009929d0eaa8fad7bd019636b9e8bde07e1a">39ac009929d0eaa8fad7bd019636b9e8bde07e1a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/3043/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/3043/jenkins-report.html">here</a>.</h5></details></html>

2022-08-07 21:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/3043/">test-portal-source-format#3043</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/3043/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lfbesada/liferay-portal/pull/96">lfbesada#96</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1939068902">[master] ci:test:sf - BarbaraCabrera &gt; lfbesada - PR#96 - 2022-08-07[14:52:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/10932/">publish-testray-report#10932</a><br/></div></div>

2022-08-08 17:53 UTC, BarbaraCabrera commented
ci:test:sf

2022-08-08 17:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/1386/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/1386/jenkins-report.html">here</a>.</b></p>

2022-08-08 17:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/88619d19282875d72fcc5aea02166c664061d25a">88619d19282875d72fcc5aea02166c664061d25a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/BarbaraCabrera/liferay-portal/tree/LPS-158711_WIP">LPS-158711_WIP</a><br/>Branch GIT ID: <a href="https://github.com/BarbaraCabrera/liferay-portal/commit/2f0707b6cab39dd1d5ecc3eb1aa5e810f7ef1aae">2f0707b6cab39dd1d5ecc3eb1aa5e810f7ef1aae</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-source-format/1386/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/1386/jenkins-report.html">here</a>.</h5></details></html>

2022-08-08 18:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/1386/">test-portal-source-format#1386</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/1386/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/lfbesada/liferay-portal/pull/96">lfbesada#96</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1939754809">[master] ci:test:sf - BarbaraCabrera &gt; lfbesada - PR#96 - 2022-08-08[10:53:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/5426/">publish-testray-report#5426</a><br/></div></div>

2022-08-09 07:28 UTC, lfbesada requested changes

2022-08-09 07:28 UTC, lfbesada commented on modules/apps/asset/asset-categories-service/src/main/java/com/liferay/asset/categories/internal/search/spi/model/index/contributor/AssetCategoryModelDocumentContributor.java
> +				descriptionAvailableLanguageIds) {
Creo que sería mejor quitar el description del nombre de la variable y que fuera availableLanguageIds, el description sería necesario si hubiera ambigüedad, otra variable similar, pero no es el caso, así que no es necesario el nombre tan largo

2022-08-09 07:28 UTC, lfbesada commented on modules/apps/commerce/commerce-product-content-category-web/src/main/resources/META-INF/resources/view.jsp
> +				<p class="category-description"><%= assetCategory.getDescription(languageId) %></p>
Esto quedaría mal, no puedes meter algo que esperas que sea HTML dentro de un tag p HTML porque tendrás un HTML incorrecto. Aquí deberías quitar el tag HTML igual que hiciste en view_asset_categories.jsp

2022-08-09 07:28 UTC, lfbesada commented on modules/apps/commerce/commerce-product-service/src/main/java/com/liferay/commerce/product/internal/search/CPDisplayLayoutIndexer.java
> +			}
Aquí se aplica todo lo comentado en el indexer de categoría:
1. No está bien, no se está haciendo lo mismo que en Journal
2. Una vez arreglado se puede no declarar description y usarlo inline
3. Rename descriptionAvailableLanguageIds -> availableLanguageIds

2022-08-24 06:36 UTC, closed without merging